package comcast.test.testSuite;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import comcast.test.app.common.helpHeaderFooterLinks.userRegTestCasesForHelpLink.VerifyHelpLink;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangeActivationCode.ChangeUserActivationCode;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangeActivationCode.ChangeActivationCodeWithInValidAC.ValidateUserActivationCodeByEnteringInvalidCode;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangeActivationCode.ChangeActivationCodeWithValidAC.ValidateUserActivationCodeUpdatesSuccessfully;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangeActivationCode.ValidateActivationCodeRequiredField.ValidateUserActivationCodeMandatoryField;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ChangePassword.ChangeUserLoginPassword;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPassword.ResetTheXidioPassword;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPasswordWithInvalidEmail.ResetTheXidioPasswordWithWrongEmail;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPasswordWithNoEmail.ResetXidioPasswordWithoutProvidingEmailID;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ValidateCurrentUserPassWhileChangingPass.ValidateCurrentPasswordWhenChangingPassword;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.ValidateNewAndConfirmPassword.ValidateNewPasswordAndConfirmPasswordMatch;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePassword.VerifyPasswordChangesSuccessfully.VerifyPasswordChangeWorks;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateChangePaymentInfoDetailsUpdatedSuccessfully;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateChangePaymentInfoMandatoryFields;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateCreditCardField.ValidatePaymentInfoCreditCardNumberWithInvalidInput;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateExpiryMonthField.ValidatePaymentInfoMonthByEnteringInvalidMonth;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateExpiryMonthField.ValidatePaymentInfoMonthMandatoryField;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateExpiryMonthField.VerifyPaymentInfoExpiryMonthUpdatedSuccessfully;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateSecurityField.ValidatePaymentInfoSecurityCodeByEnteringCharacters;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateSecurityField.ValidatePaymentInfoSecurityCodeWithInvalidInputLength;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateYearField.ValidatePaymentInfoYearFieldByEnteringPastYear;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateYearField.ValidatePaymentInfoYearMandatoryField;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ChangePinCode;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ValidateChangePinCodeAllMandatoryFields;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.VerifyChangePinCodeDetailsUpdatedSuccessfully;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ValidatePasswordField.ValidateChangePasswordByEnteringInvalidPass;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ValidatePasswordField.VerifyEnteredPasswordIsVisibleWhenUserClicksOnDisplayPass;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ValidatePinCodeField.ValidateChangePinCodeByEnteringInvalidPinLength;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForChangePinCode.ValidatePinCodeField.VerifyEnteredPinIsVisibleWhenUserClicksOnDisplayPin;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateAddressField.EditXidioAddressInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateAddressField.ValidateAddressFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateCityField.EditXidioCityInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateCityField.ValidateCityFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateEmailField.EditXidioUserEmail;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateEmailField.ValidateEmailFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateEmailField.ValidateEmailFieldByEnteringInvalidEmailID;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateFirstNameField.EditXidioFirstNameInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateFirstNameField.ValidateFirstNameFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateLastNameField.EditXidioLastNameInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateLastNameField.ValidateLastNameFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateMobileNumberField.ExitXidioUserMobileNumber;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateMobileNumberField.ValidateMobileNumberFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateMobileNumberField.ValidateMobileNumberFieldByEnteringExistingNo;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateMobileNumberField.ValidateMobileNumberFieldByEnteringInvalidNo;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateStateField.EditXidioStateInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateZipField.EditXidioZipInProfileManagement;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateZipField.ValidateZipFieldByDeletingValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateZipField.ValidateZipFieldByEnteringCharactersValue;
import comcast.test.app.testCases.userManagement.profileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateZipField.ValidateZipFieldByEnteringInvalidZipLength;
import comcast.test.app.testCases.userManagement.userLogin.ValidateLoginScreen.CheckEmptyUsernameAndPasswordTextBoxes;
import comcast.test.app.testCases.userManagement.userLogin.ValidateLoginScreen.VerifyHelpLinkInLoginPage;
import comcast.test.app.testCases.userManagement.userLogin.ValidateLoginScreen.VerifyRegisterLinks;
import comcast.test.app.testCases.userManagement.userLogin.ValidateSignOutWorks.CheckSignOutFunctionality;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingDigits;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidPassword;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidUserName;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingJavaScript;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingSQLKeyWords;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingSQLStatement;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingSpecialCharacters;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationWithInValidCredentials;
import comcast.test.app.testCases.userManagement.userLogin.ValidateUserLoginUsingValidCredentials.LoginToXidioApplicationWithValidCredentials;
import comcast.test.app.testCases.userManagement.userRegistration.RegisterToXidioApplicationUsingValidCredentials;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForActivationCode.UserRegByClickingOnActivationCode.RegisterToXidioApplicationByClickingActivation;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForActivationCode.UserRegBySkipingActivationCode.RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForActivationCode.UserRegWithoutActivationCode.RegisterUserWithoutActivationCode;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForAddress.UserRegWithNoAddress.RegisterToXidioApplicationWithoutEnteringAddress;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCity.UserRegWithNoCity.RegisterToXidioApplicationWithoutEnteringCity;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegToCheckDiplayPasswordCheckboxWorks.RegisterToXidioApplicationWithCheckingDiplayPasswordCheckbox;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegToCheckDiplayPinCheckboxWorks.RegisterToXidioApplicationWithCheckingDiplayPinCheckbox;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithInvalidCCNumber.RegisterToXidioApplicationWithInvalidCreditCardNumber;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithInvalidPin.UserRegWithInvalidPinCodeCharLength.RegisterToXidioApplicationWithInvalidPinCodeCharLength;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithInvalidSecurityCode.UserRegWithInvalidSecurityCodeLength.ValidateInvalidSecurityCodeLength;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithInvalidSecurityCode.UserRegWithInvalidSecurityCodeSplCharacters.ValidateInvalidSCWithSplChar;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithNoCCNumber.RegisterToXidioApplicationWithNoCreditCardNumber;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithNoPINCode.RegisterToXidioApplicationWithNoPinCode;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForCreditCardDetails.UserRegWithNoSecurityCode.RegisterToXidioApplicationWithNoSecurityCode;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForEmail.UserRegWithInvalidEmailID.UserRegWithInvalidEmailIDMissingInputs.RegisterToXidioApplicationByEnteringInValidEmail;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForEmail.UserRegWithNoEmailID.RegisterToXidioApplicationWithoutEnteringEmail;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForFirstName.UserRegWithNoFirstName.RegisterToXidioApplicationWithoutEnteringFirstName;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForLastName.UserRegWithNoLastName.RegisterToXidioApplicationWithoutEnteringLastName;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForLastName.UserRegWithValidLastName.RegisterToXidioApplicationByEnteringValidLastName;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForMobileNumber.UserRegWithInvalidMobileNumber.RegisterToXidioApplicationByEnteringInValidMobileNumber;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForMobileNumber.UserRegWithNoMobileNumber.RegisterToXidioApplicationWithoutEnteringMobileNumber;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForPassword.UserRegWithInvalidPasswordLength.RegisterToXidioApplicationByEnteringInValidLengthOfPassword;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForPassword.UserRegWithNoFirstCapitalLetter.RegisterToXidioApplicationByEnteringNonCapitalLetterPassword;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForPassword.UserRegWithNoPassword.RegisterToXidioApplicationWithoutEnteringPassword;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForPassword.UserRegWithNonDigitPassword.RegisterToXidioApplicationByEnteringNonDigitPassword;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForPaymentDetails.RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForTermsAndCondition.UserRegByDeclineTermAndCondition.RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForZipCode.UserRegWithInvalidZipCode.RegisterToXidioApplicationByEnteringInValidZip;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForZipCode.UserRegWithInvalidZipCodeLength.RegisterToXidioApplicationByEnteringInValidZipLength;
import comcast.test.app.testCases.userManagement.userRegistration.UserRegistrationTestCasesForZipCode.UserRegWithNoZipCode.RegisterToXidioApplicationWithoutEnteringZip;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.EnsureRowsShowsVideosAreDisplayedForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyDropDownCategoriesForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyShowCountForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyUpdatedStatusForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyVideoCountForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.RowsCategory.VerifyShowsAndVideosInRowsForHomeFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyShowsUnderChannelForHomeFeatured;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyUpdatedStatusForHomeFeaturedShow;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyVideoCountForHomeFeaturedShow;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.ChannelTestCases.VideosCategory.VerifyVideosUnderChannelForHomeFeatured;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyChannelIsDisplayedUnderHomeFeaturedCategoryPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyShowIsDisplayedUnderHomeFeaturedCategoryPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyVideosAndNextLinkInHomeFeaturedPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.FeaturedCategoryTestCases.PaginationTestCases.VerifyHomeFeaturedCategoryPaginationFunctionality;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.HomePageTestCases.VerifyAllHomeCategoriesAreDisplayed;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.HomePageTestCases.VerifyHomeCategoryVideosAreDisplayed;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ChannelPageTestCases.EnsureRowsShowsVideosAreDisplayedForPopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyDropDownCategoriesForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyShowCountForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyUpdatedStatusForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyVideoCountForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.RowsCategory.VerifyShowsAndVideosInRowsForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyShowsUnderChannelForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyUpdatedStatusForHomePopularChannelShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyVideoCountForHomePopularChannelShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.ChannelTestCases.VideosCategory.VerifyVideosUnderChannelForHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.PaginationTestCases.VerifyHomePopularChannelsCategoryPaginationWorksFine;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.PopularChannelCategoryPageTestCases.VerifyChannelIsDisplayedUnderHomePopularChannelsCategoryPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularChannelsCategoryTestCases.PopularChannelCategoryPageTestCases.VerifyVideosAndNextLinkInHomePopularChannelsPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.PaginationTestCases.VerifyHomePopularShowsCategoryPaginationFunctionality;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.PopularShowsCategoryPageTestCases.VerifyNextAndPreviousLinksForPopularShowsCategory;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.PopularShowsCategoryPageTestCases.VerifyShowsAreDisplayedUnderHomePopularShowsCategoryPage;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.ShowsDetailsPageTestCases.VerifyDropDownCategoriesForHomePopularShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.ShowsDetailsPageTestCases.VerifyUpdatedStatusForHomePopularShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.ShowsDetailsPageTestCases.VerifyVideoCountForHomePopularShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.PopularShowsCategoryTestCases.ShowsDetailsPageTestCases.VerifyVideosUnderHomePopularShows;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.UpNextCategoryTestCases.PaginationTestCases.VerifyNextAndPreviousLinksForUpNextVideoCategory;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.UpNextCategoryTestCases.PaginationTestCases.VerifyPaginationForUpNextVideoCategory;
import comcast.test.app.testCases.videoManagement.videoHomeManagement.UpNextCategoryTestCases.UpNextCategoryPageTestCases.VerifyVideosAreDisplayedUnderUpNextCategoryPage;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoBySelectingChannelAndThenShow;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoBySelectingShowInHomePage;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoFromRows;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoFromRowsByClickingOnShow;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoSelectingFromShows;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.FeaturedVideos.PlayHomeFeaturedVideoSelectingFromVideos;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularChannelsVideos.PlayHomePopularChannelsVideoBySelectingChannelAndThenShow;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularChannelsVideos.PlayHomePopularChannelsVideoFromRows;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularChannelsVideos.PlayHomePopularChannelsVideoFromRowsByClickingOnShow;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularChannelsVideos.PlayHomePopularChannelsVideoSelectingFromShows;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularChannelsVideos.PlayHomePopularChannelsVideoSelectingFromVideos;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.PopularShowsVideo.PlayHomePopularShowsVideoFromList;
import comcast.test.app.testCases.videoManagement.videoPlay.HomeCategoryVideos.UpNextVideos.PlayVideoFromUpNextCategory;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoBySelectingChannelAndThenShow;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoBySelectingShowInStorePage;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoFromRows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoFromRowsByClickingOnShow;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoSelectingFromShows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.FeaturedVideos.PlayFeaturedVideoSelectingFromVideos;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.PopularVideos.PlayPopularVideoBySelectingChannelAndThenShows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.PopularVideos.PlayPopularVideoFromRows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.PopularVideos.PlayPopularVideoFromRowsByClickingOnShows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.PopularVideos.PlayPopularVideoSelectingFromShows;
import comcast.test.app.testCases.videoManagement.videoPlay.StoreCategoryVideos.PopularVideos.PlayPopularVideoSelectingFromVideos;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscribedChannelVideoTestCases.PlaySubscribedChannelVideoBySelectingChannelAndThenShow;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscribedChannelVideoTestCases.PlaySubscribedChannelVideoBySelectingRowsInChannelDetailsPage;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscribedChannelVideoTestCases.PlaySubscribedChannelVideoFromRowsByClickingOnShow;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscribedChannelVideoTestCases.PlaySubscribedChannelVideoSelectingFromShows;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscribedChannelVideoTestCases.PlaySubscribedChannelVideoSelectingFromVideos;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscriptionsPageVideoTestCases.PlaySubscribedChannelVideoBySelectingRowsInSubscriptionsPage;
import comcast.test.app.testCases.videoManagement.videoPlay.SubscriptionsCategoryVideos.SubscriptionsPageVideoTestCases.PlaySubscribedChannelVideoBySelectingShowsInSubscriptionsPage;
import comcast.test.app.testCases.videoManagement.videoSearch.searchVideoByCategory.EnsureSearchChannelStoreIsWorkingFine;
import comcast.test.app.testCases.videoManagement.videoSearch.searchVideoByCategory.VerifySubscriptionsCategoryVideosAreDisplayed;
import comcast.test.app.testCases.videoManagement.videoSearch.searchVideoByInvalidData.VerifySearchByEnteringSplCharacters;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.EnsureRowsShowsVideosAreDisplayedForAChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyDropDownCategoriesForFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyShowCountForAFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyUpdatedStatusForAFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyVideoCountForAFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.RowsCategory.VerifyShowsAndVideosInRowsForFeaturedChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyShowsUnderChannelForFeatured;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyUpdatedStatusForAFeaturedShows;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyVideoCountForAFeaturedShows;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.ChannelTestCases.VideosCategory.VerifyVideosUnderChannelForFeatured;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyChannelIsDisplayedUnderFeaturedCategoryPage;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyShowIsDisplayedUnderFeaturedCategoryPage;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.FeaturedCategoryPageTestCases.VerifyVideosAndNextLinkInFeaturedStorePage;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.FeaturedCategoryTestCases.PaginationTestCases.VerifyFeaturedCategoryPaginationFunctionality;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyDropDownCategoriesForPopularChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyShowCountForAPopularChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyUpdatedStatusForAPopularChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ChannelPageTestCases.VerifyVideoCountForAPopularChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.RowsCategory.VerifyShowsAndVideosInRowsForPopularChannel;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyShowsUnderChannelForPopular;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyUpdatedStatusForAPopularShows;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.ShowsCategory.VerifyVideoCountForAPopularShows;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.ChannelTestCases.VideosCategory.VerifyVideosUnderChannelForPopular;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.PaginationTestCases.VerifyPopularCategoryPaginationFunctionality;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.PopularCategoryPageTestCases.VerifyChannelIsDisplayedUnderPopularCategory;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.PopularCategoryTestCases.PopularCategoryPageTestCases.VerifyVideosAndNextLinkInPopularStorePage;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.StorePageTestCases.EnsureStoreIsSelectedAsDefault;
import comcast.test.app.testCases.videoManagement.videoStoreManagement.StorePageTestCases.VerifyStoreCategoryVideosAreDisplayed;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.EnsureRowsShowsVideosAreDisplayedForSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.VerifyDropDownCategoriesForSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.VerifyShowCountForASubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.VerifyUpdatedStatusForSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.VerifyVideoCountForSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ChannelPageTestCases.VerifyVideosAndNextLinkInSubscribedChannelDetailsPage;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.RowsCategory.VerifyShowsAndVideosInRowsForSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ShowsCategory.VerifyShowsUnderSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.ShowsCategory.VerifyVideoByClickingOnShowUnderSubscriptionsShows;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscribedChannelTestCases.VideosCategory.VerifyVideosUnderSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.ChannelsCategory.VerifySubscribedChannelsUnderSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.RowsCategory.VerifyRowsVideosForSubscribedChannelInSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.ShowsCategory.VerifyShowsForSubscribedChannelInSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.ShowsCategory.VerifyVideoByClickingOnShowUnderSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.SubscriptionsDetailPage.EnsureRowsChannelsAndShowsAreDisplayedInSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.SubscriptionsDetailPage.VerifyDropDownCategoriesForSubscribedChannelPage;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.SubscriptionsDetailPage.VerifySubscribedChannelIsDisplayedUnderSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.SubscriptionsDetailPage.VerifySubscriptionScreenHasLogoLinksAndWelcomeMessage;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscribedChannelTestCases.SubscriptionsPageTestCases.SubscriptionsDetailPage.VerifyVideosNextAndPreviousLinksWorksInSubscriptions;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromHomeCategory.SubscriptionOfChannel.SubscribeAFreeChannelFromHomeFeaturedCategory;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromHomeCategory.SubscriptionOfChannel.SubscribeAFreeChannelFromHomePopularChannelsCategory;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromHomeCategory.UnsubscriptionOfChannel.UnsubscribeAHomeFeaturedSubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromHomeCategory.UnsubscriptionOfChannel.UnsubscribeASubscribedChannelFromHomePopularChannels;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromStoreCategory.SubscriptionOfChannel.SubscribeAFreeChannelFromFeaturedCategory;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.freeSubscriptionOfVideosFromStoreCategory.UnsubscriptionOfChannel.UnsubscribeASubscribedChannel;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.paidSubscriptionForVideo.SearchAndSubscribeVideo;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.paidSubscriptionForVideo.UnsubscribeUserSubscribedVideo;
import comcast.test.app.testCases.videoManagement.videoSubscriptionManagement.paidSubscriptionForVideo.VerifySubcriptionOfPaidVideo;

@RunWith(Suite.class)
@Suite.SuiteClasses({ 
	/*
	 * TOTAL: 222 Test cases are Mapped.
	 * Description: 27 Test cases are commented because of functionality changes.  
	 */
	
	/* Module: User Login Module Test cases.
	 * Count: 14
	 */
	
	LoginToXidioApplicationWithValidCredentials.class,
	LoginToXidioApplicationUsingInValidUserName.class,
	LoginToXidioApplicationUsingInValidPassword.class,
	LoginToXidioApplicationUsingDigits.class,
	LoginToXidioApplicationUsingJavaScript.class,
	LoginToXidioApplicationUsingSpecialCharacters.class,
	LoginToXidioApplicationUsingSQLKeyWords.class,
	LoginToXidioApplicationUsingSQLStatement.class,
	LoginToXidioApplicationWithInValidCredentials.class,
	CheckEmptyUsernameAndPasswordTextBoxes.class,
	VerifyRegisterLinks.class,
	VerifyHelpLinkInLoginPage.class,
	CheckSignOutFunctionality.class,
	VerifyHelpLink.class,
	
	/* Module: User Registration Management Test cases.
	 * Count: 31*/
	//START : UserRegistrationTestCasesForActivationCode
	/*RegisterToXidioApplicationByClickingActivation.class,
	RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep.class,
	RegisterUserWithoutActivationCode.class,*/
	//END
	
	//START : UserRegistrationTestCasesForCreditCardDetails
	/*RegisterToXidioApplicationWithCheckingDiplayPasswordCheckbox.class,
	RegisterToXidioApplicationWithCheckingDiplayPinCheckbox.class,
	RegisterToXidioApplicationWithInvalidCreditCardNumber.class,	
	RegisterToXidioApplicationWithInvalidPinCodeCharLength.class,
	ValidateInvalidSecurityCodeLength.class,
	ValidateInvalidSCWithSplChar.class,
	RegisterToXidioApplicationWithNoCreditCardNumber.class,
	RegisterToXidioApplicationWithNoPinCode.class,
	RegisterToXidioApplicationWithNoSecurityCode.class,
	RegisterToXidioApplicationByEnteringValidLastName.class,*/
	//END
	
	RegisterToXidioApplicationUsingValidCredentials.class,	
	RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition.class,
	RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo.class,
	RegisterToXidioApplicationWithoutEnteringFirstName.class,
	RegisterToXidioApplicationWithoutEnteringLastName.class,
	RegisterToXidioApplicationWithoutEnteringAddress.class,
	RegisterToXidioApplicationWithoutEnteringCity.class,
	RegisterToXidioApplicationWithoutEnteringZip.class,
	RegisterToXidioApplicationWithoutEnteringEmail.class,
	RegisterToXidioApplicationByEnteringInValidEmail.class,
	RegisterToXidioApplicationByEnteringInValidZip.class,
	RegisterToXidioApplicationByEnteringInValidZipLength.class,
	RegisterToXidioApplicationWithoutEnteringMobileNumber.class,
	RegisterToXidioApplicationByEnteringInValidMobileNumber.class,
	RegisterToXidioApplicationWithoutEnteringPassword.class,
	RegisterToXidioApplicationByEnteringNonCapitalLetterPassword.class,
	RegisterToXidioApplicationByEnteringNonDigitPassword.class,
	RegisterToXidioApplicationByEnteringInValidLengthOfPassword.class,
	
	
	/* Module: Profile Management Test cases.
	 * Count: 48
	 */
	
	//START: RegisteredUserTestCasesForChangeActivationCode
/*	ValidateUserActivationCodeByEnteringInvalidCode.class,
	ValidateUserActivationCodeUpdatesSuccessfully.class,
	ValidateUserActivationCodeMandatoryField.class,
	ChangeUserActivationCode.class,*/
	//END
	
	//START: RegisteredUserTestCasesForChangePassword
	/*ChangeUserLoginPassword.class,*/
	ResetTheXidioPassword.class,
	ResetTheXidioPasswordWithWrongEmail.class,
	ResetXidioPasswordWithoutProvidingEmailID.class,
	ValidateCurrentPasswordWhenChangingPassword.class,
	ValidateNewPasswordAndConfirmPasswordMatch.class,
	VerifyPasswordChangeWorks.class,
	//END
	
	//START: RegisteredUserTestCasesForChangePaymentInfo
/*	ValidatePaymentInfoCreditCardNumberWithInvalidInput.class,
	ValidatePaymentInfoMonthByEnteringInvalidMonth.class,
	ValidatePaymentInfoMonthMandatoryField.class,
	VerifyPaymentInfoExpiryMonthUpdatedSuccessfully.class,
	ValidatePaymentInfoSecurityCodeByEnteringCharacters.class,
	ValidatePaymentInfoSecurityCodeWithInvalidInputLength.class,	
	ValidatePaymentInfoYearFieldByEnteringPastYear.class,	
	ValidatePaymentInfoYearMandatoryField.class,
	ValidateChangePaymentInfoDetailsUpdatedSuccessfully.class,
	ValidateChangePaymentInfoMandatoryFields.class,*/
	//END
	
	//START: RegisteredUserTestCasesForChangePinCode
	ValidateChangePasswordByEnteringInvalidPass.class,
	VerifyEnteredPasswordIsVisibleWhenUserClicksOnDisplayPass.class,
	ValidateChangePinCodeByEnteringInvalidPinLength.class,
	VerifyEnteredPinIsVisibleWhenUserClicksOnDisplayPin.class,
	ChangePinCode.class,
	ValidateChangePinCodeAllMandatoryFields.class,
	VerifyChangePinCodeDetailsUpdatedSuccessfully.class,
	//END
	
	//START: RegisteredUserTestCasesForEditProfileDetails
	EditXidioAddressInProfileManagement.class,
	ValidateAddressFieldByDeletingValue.class,
	
	EditXidioCityInProfileManagement.class,
	ValidateCityFieldByDeletingValue.class,
	
	EditXidioUserEmail.class,
	ValidateEmailFieldByDeletingValue.class,
	ValidateEmailFieldByEnteringInvalidEmailID.class,
	
	EditXidioFirstNameInProfileManagement.class,
	ValidateFirstNameFieldByDeletingValue.class,
	
	EditXidioLastNameInProfileManagement.class,
	ValidateLastNameFieldByDeletingValue.class,
	
	ExitXidioUserMobileNumber.class,
	ValidateMobileNumberFieldByDeletingValue.class,
	ValidateMobileNumberFieldByEnteringInvalidNo.class,
	ValidateMobileNumberFieldByEnteringExistingNo.class,
	
	EditXidioStateInProfileManagement.class,
	
	EditXidioZipInProfileManagement.class,
	ValidateZipFieldByDeletingValue.class,
	ValidateZipFieldByEnteringCharactersValue.class,
	ValidateZipFieldByEnteringInvalidZipLength.class,
	//END

	
	/* Module: Video Management Test cases.
	 * VideoPlay Store Categroy
	 * Count: 11*/
	PlayFeaturedVideoBySelectingChannelAndThenShow.class,
	PlayFeaturedVideoBySelectingShowInStorePage.class,
	PlayFeaturedVideoFromRowsByClickingOnShow.class,
	PlayFeaturedVideoFromRows.class,
	PlayFeaturedVideoSelectingFromShows.class,
	PlayFeaturedVideoSelectingFromVideos.class,
	PlayPopularVideoBySelectingChannelAndThenShows.class,
	PlayPopularVideoFromRows.class,
	PlayPopularVideoFromRowsByClickingOnShows.class,
	PlayPopularVideoSelectingFromShows.class,
	PlayPopularVideoSelectingFromVideos.class,
	
	/* Module: Video Management Test cases.
	 * VideoPlay Home Categroy
	 * Count: 13 */
	PlayVideoFromUpNextCategory.class,
	PlayHomeFeaturedVideoBySelectingChannelAndThenShow.class,
	PlayHomeFeaturedVideoBySelectingShowInHomePage.class,
	PlayHomeFeaturedVideoFromRowsByClickingOnShow.class,
	PlayHomeFeaturedVideoFromRows.class,
	PlayHomeFeaturedVideoSelectingFromShows.class,
	PlayHomeFeaturedVideoSelectingFromVideos.class,
	PlayHomePopularChannelsVideoBySelectingChannelAndThenShow.class,
	PlayHomePopularChannelsVideoFromRows.class,
	PlayHomePopularChannelsVideoFromRowsByClickingOnShow.class,
	PlayHomePopularChannelsVideoSelectingFromShows.class,
	PlayHomePopularChannelsVideoSelectingFromVideos.class,
	PlayHomePopularShowsVideoFromList.class,
	
	/* Module: Video Management Test cases.
	 * VideoPlay Subscriptions Categroy
	 * Count: 7 */
	PlaySubscribedChannelVideoBySelectingChannelAndThenShow.class,
	PlaySubscribedChannelVideoBySelectingRowsInChannelDetailsPage.class,
	PlaySubscribedChannelVideoFromRowsByClickingOnShow.class,
	PlaySubscribedChannelVideoSelectingFromShows.class,
	PlaySubscribedChannelVideoSelectingFromVideos.class,
	PlaySubscribedChannelVideoBySelectingRowsInSubscriptionsPage.class,
	PlaySubscribedChannelVideoBySelectingShowsInSubscriptionsPage.class,
	
	/*videoStoreManagement Featured Category Test cases.
	 * Count:14 
	 */
	EnsureRowsShowsVideosAreDisplayedForAChannel.class,
	VerifyDropDownCategoriesForFeaturedChannel.class,
	VerifyShowCountForAFeaturedChannel.class,
	VerifyUpdatedStatusForAFeaturedChannel.class,
	VerifyVideoCountForAFeaturedChannel.class,
	VerifyShowsAndVideosInRowsForFeaturedChannel.class,
	VerifyShowsUnderChannelForFeatured.class,
	VerifyVideosUnderChannelForFeatured.class,
	VerifyChannelIsDisplayedUnderFeaturedCategoryPage.class,
	VerifyShowIsDisplayedUnderFeaturedCategoryPage.class,
	VerifyVideosAndNextLinkInFeaturedStorePage.class,
	VerifyFeaturedCategoryPaginationFunctionality.class,
	VerifyUpdatedStatusForAFeaturedShows.class,
	VerifyVideoCountForAFeaturedShows.class,
	
	/*videoStoreManagement Popular Category Test cases.
	 * Count: 15
	 */
	EnsureRowsShowsVideosAreDisplayedForAChannel.class,
	VerifyDropDownCategoriesForPopularChannel.class,
	VerifyShowCountForAPopularChannel.class,
	VerifyUpdatedStatusForAPopularChannel.class,
	VerifyVideoCountForAPopularChannel.class,
	VerifyShowsAndVideosInRowsForPopularChannel.class,
	VerifyShowsUnderChannelForPopular.class,
	VerifyVideosUnderChannelForPopular.class,
	VerifyPopularCategoryPaginationFunctionality.class,
	VerifyChannelIsDisplayedUnderPopularCategory.class,
	VerifyVideosAndNextLinkInPopularStorePage.class,
	EnsureStoreIsSelectedAsDefault.class,
	VerifyStoreCategoryVideosAreDisplayed.class,
	VerifyUpdatedStatusForAPopularShows.class,
	VerifyVideoCountForAPopularShows.class,
	
	/*videoHomeManagement Featured Category Test cases.
	 * Count: 16
	 */
	EnsureRowsShowsVideosAreDisplayedForHomeFeaturedChannel.class,
	VerifyDropDownCategoriesForHomeFeaturedChannel.class,
	VerifyShowCountForHomeFeaturedChannel.class,
	VerifyUpdatedStatusForHomeFeaturedChannel.class,
	VerifyVideoCountForHomeFeaturedChannel.class,
	VerifyShowsAndVideosInRowsForHomeFeaturedChannel.class,
	VerifyShowsUnderChannelForHomeFeatured.class,
	VerifyVideosUnderChannelForHomeFeatured.class,
	VerifyChannelIsDisplayedUnderHomeFeaturedCategoryPage.class,
	VerifyShowIsDisplayedUnderHomeFeaturedCategoryPage.class,
	VerifyVideosAndNextLinkInHomeFeaturedPage.class,
	VerifyHomeFeaturedCategoryPaginationFunctionality.class,
	VerifyAllHomeCategoriesAreDisplayed.class,
	VerifyHomeCategoryVideosAreDisplayed.class,
	VerifyUpdatedStatusForHomeFeaturedShow.class,
	VerifyVideoCountForHomeFeaturedShow.class,
	
	/*videoHomeManagement Popular Channel Category Test cases.
	 * Count: 13
	 */
	EnsureRowsShowsVideosAreDisplayedForPopularChannels.class,
	VerifyDropDownCategoriesForHomePopularChannels.class,
	VerifyShowCountForHomePopularChannels.class,
	VerifyUpdatedStatusForHomePopularChannels.class,
	VerifyVideoCountForHomePopularChannels.class,
	VerifyShowsAndVideosInRowsForHomePopularChannels.class,
	VerifyShowsUnderChannelForHomePopularChannels.class,
	VerifyVideosUnderChannelForHomePopularChannels.class,
	VerifyHomePopularChannelsCategoryPaginationWorksFine.class,
	VerifyChannelIsDisplayedUnderHomePopularChannelsCategoryPage.class,
	VerifyVideosAndNextLinkInHomePopularChannelsPage.class,
	VerifyUpdatedStatusForHomePopularChannelShows.class,
	VerifyVideoCountForHomePopularChannelShows.class,
	
	/*videoHomeManagement Popular Show Category Test cases.
	 * Count: 7
	 */
	VerifyHomePopularShowsCategoryPaginationFunctionality.class,
	VerifyNextAndPreviousLinksForPopularShowsCategory.class,
	VerifyShowsAreDisplayedUnderHomePopularShowsCategoryPage.class,
	VerifyDropDownCategoriesForHomePopularShows.class,
	VerifyUpdatedStatusForHomePopularShows.class,
	VerifyVideoCountForHomePopularShows.class,
	VerifyVideosUnderHomePopularShows.class,
	
	/*videoHomeManagement UpNext Category Test cases.
	 * Count: 3
	 */
	VerifyNextAndPreviousLinksForUpNextVideoCategory.class,
	VerifyPaginationForUpNextVideoCategory.class,
	VerifyVideosAreDisplayedUnderUpNextCategoryPage.class,
	
	/*videoSubscriptionManagement: freeSubscribedChannel > SubscribedChannel Test cases.
	 * Count: 10
	 */
	EnsureRowsShowsVideosAreDisplayedForSubscribedChannel.class,
	VerifyDropDownCategoriesForSubscribedChannel.class,
	VerifyShowCountForASubscribedChannel.class,
	VerifyUpdatedStatusForSubscribedChannel.class,
	VerifyVideoCountForSubscribedChannel.class,
	VerifyVideosAndNextLinkInSubscribedChannelDetailsPage.class,
	VerifyShowsAndVideosInRowsForSubscribedChannel.class,
	VerifyShowsUnderSubscribedChannel.class,
	VerifyVideoByClickingOnShowUnderSubscriptionsShows.class,
	VerifyVideosUnderSubscribedChannel.class,
	
	/*videoSubscriptionManagement: freeSubscribedChannel > SubscriptionsPage Test cases.
	 * Count: 9
	 */
	VerifySubscribedChannelsUnderSubscriptions.class,
	VerifyRowsVideosForSubscribedChannelInSubscriptions.class,
	VerifyShowsForSubscribedChannelInSubscriptions.class,
	VerifyVideoByClickingOnShowUnderSubscribedChannel.class,
	EnsureRowsChannelsAndShowsAreDisplayedInSubscriptions.class,
	VerifyDropDownCategoriesForSubscribedChannelPage.class,
	VerifySubscribedChannelIsDisplayedUnderSubscriptions.class,
	VerifyVideosNextAndPreviousLinksWorksInSubscriptions.class,
	VerifySubscriptionScreenHasLogoLinksAndWelcomeMessage.class,
	
	/*freeSubscriptionOfVideosFromHomeCategory Test Cases.
	 * Count: 4
	 */
	SubscribeAFreeChannelFromHomeFeaturedCategory.class,
	SubscribeAFreeChannelFromHomePopularChannelsCategory.class,
	UnsubscribeAHomeFeaturedSubscribedChannel.class,
	UnsubscribeASubscribedChannelFromHomePopularChannels.class,
	
	/*freeSubscriptionOfVideosFromStoreCategory Test Cases.
	 * Count: 2
	 */
	SubscribeAFreeChannelFromFeaturedCategory.class,
	UnsubscribeASubscribedChannel.class,

	/*videoSearch Module Test Cases.
	 * Count: 3
	 */
	EnsureSearchChannelStoreIsWorkingFine.class,
	VerifySearchByEnteringSplCharacters.class,
	VerifySubscriptionsCategoryVideosAreDisplayed.class,

	/*videoSubscriptionManagement> paidSubscriptionForVideo Test Cases.
	 * Count: 3
	 */
	SearchAndSubscribeVideo.class,
	UnsubscribeUserSubscribedVideo.class,
	VerifySubcriptionOfPaidVideo.class

})
public class runATFRegressionV2 {

}
